vim.opt.relativenumber=true
vim.opt.number=true
vim.opt.encoding='utf-8'
vim.opt.swapfile=false
vim.opt.scrolloff=7
vim.opt.shiftwidth=2
vim.opt.tabstop=2
vim.opt.softtabstop=2
vim.opt.autoindent=true
vim.opt.expandtab=true
vim.opt.smartindent=true
vim.opt.fileformat='unix'
vim.opt.mouse= 'a'
vim.opt.syntax= 'on'
vim.opt.cursorline= true
vim.opt.cursorlineopt= 'both'
vim.completeopt='menu,menuone,noselect'
vim.opt.termguicolors=true
vim.cmd[[colorscheme gruvbox]]
vim.cmd[[set colorcolumn=79]]
