#! /bin/bash

#ВОРКСПЕЙСЫ
bspc monitor -d     


#РАМКИ И ГАПСЫ
bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "fd2e59"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))



#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5
#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	   false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle	true


#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
#bspc config automatic_scheme	spiral


#ПРАВИЛА ОКОН
bspc rule -a firefox desktop='^1'
bspc rule -a TelegramDesktop desktop='^2'
#bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
bspc rule -a Steam desktop='^5'
bspc rule -a VSCodium desktop='^3'
bspc rule -a Vmware desktop='^4'

#АВТОСТАРТ
sxhkd &
numlockx on &
nitrogen --restore &
picom --config .config/picom/picom.conf --experimental-backends -b &
xsetroot -cursor_name left_ptr &
firefox &
telegram-desktop &
vscodium &
# steam &
setxkbmap -model pc105 -layout us,ua -option grp:alt_shift_toggle &
bash /home/arfors/.config/polybar/launch.sh
python3 /home/arfors/.config/scripts/firefox.py &
